name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: soterfernandes
          template: classic
          base: header, activity, metadata
          config_timezone: America/Sao_Paulo
          config_display: large
          filename: github-metrics.svg
          committer_branch: main
          committer_message: "chore: update github metrics"